# matugen — kitty renkleri
background            #0d0b09
foreground            #f1e6d8
selection_background  #ff9a2f
selection_foreground  #0d0b09
cursor                #ff9a2f
cursor_text_color     #0d0b09

# normal renkler
color0   #19120e
color1   #d51110
color2   #ff9a2f
color3   #eb7c2b
color4   #7a5d7c
color5   #7f8c8d
color6   #ffc37a
color7   #f1e6d8
# Parlak renkler
color8   #463222
color9   #ef2a29
color10  #ffb362
color11  #ef995a
color12  #957597
color13  #9aa4a5
color14  #ffdaad
color15  #f1e6d8
