general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl eval 'hl.dsp.dpms("on")'
    ignore_dbus_inhibit = false             
    ignore_systemd_inhibit = false          
    inhibit_sleep = 2
}

# 1. Ekranları Karart (2.5 dk - Laptop & HDMI)
listener {
    timeout = 150                                
    on-timeout = brightnessctl -s set 10; ddcutil setvcp 10 10 --display 1 2>/dev/null &
    on-resume = brightnessctl -r; ddcutil setvcp 10 50 --display 1 2>/dev/null &
}

# 2. Ekranı Kilitle (5.0 dk)
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# 3. Ekranları Kapat (5.5 dk - Hyprland Lua DPMS)
listener {
    timeout = 330                                                     
    on-timeout = hyprctl eval 'hl.dsp.dpms("off")'
    on-resume = hyprctl eval 'hl.dsp.dpms("on")'
}

# 4. Askıya Al / Uyku (30 dk)
listener {
    timeout = 1800                                
    on-timeout = systemctl suspend                
}
