wallpaper {
	monitor = eDP-1
	path = ~/Pictures/584851757_860848453005722_4605576253667356261_n.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/Pictures/images.steamusercontent.jpg
	fit_mode = cover
}
