-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@120.00", position = "1920x0", scale = 1.00 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@100.00", position = "0x0", scale = 1.00 })
