function apply-theme
    set -l color_file "$HOME/.config/oomox/colors/hlorange"

    if not test -f $color_file
        echo ":: HATA: Renk dosyası bulunamadı: $color_file"
        return 1
    end

    # ── 1. GTK & Materia ──────────────────────────────────────────────────────
    echo ":: [1/4] GTK & Materia teması derleniyor..."
    oomox-materia-cli -o hlorange $color_file
    and echo ":: GTK teması ~/.themes/hlorange altına kuruldu."
    or echo ":: UYARI: Materia derlemesi başarısız."

    # ── 2. Kvantum (Qt uygulamaları) ──────────────────────────────────────────
    echo ":: [2/4] Kvantum senkronize ediliyor..."
    set -l kv_cfg "$HOME/.config/Kvantum/kvantum.kvconfig"
    if test -f $kv_cfg
        sed -i 's/^theme=.*/theme=hlorange/' $kv_cfg
        echo ":: Kvantum → hlorange teması seçildi."
    else
        echo ":: Kvantum config bulunamadı, atlıyorum."
    end

    # ── 3. Kitty terminal renkleri ────────────────────────────────────────────
    echo ":: [3/4] Kitty renkleri yazılıyor..."
    set -l bg  (grep "^BG="                  $color_file | cut -d= -f2)
    set -l fg  (grep "^FG="                  $color_file | cut -d= -f2)
    set -l acc (grep "^TERMINAL_ACCENT_COLOR=" $color_file | cut -d= -f2)
    set -l sel (grep "^SEL_BG="              $color_file | cut -d= -f2)

    set -l c0  (grep "^TERMINAL_COLOR0="  $color_file | cut -d= -f2)
    set -l c1  (grep "^TERMINAL_COLOR1="  $color_file | cut -d= -f2)
    set -l c2  (grep "^TERMINAL_COLOR2="  $color_file | cut -d= -f2)
    set -l c3  (grep "^TERMINAL_COLOR3="  $color_file | cut -d= -f2)
    set -l c4  (grep "^TERMINAL_COLOR4="  $color_file | cut -d= -f2)
    set -l c5  (grep "^TERMINAL_COLOR5="  $color_file | cut -d= -f2)
    set -l c6  (grep "^TERMINAL_COLOR6="  $color_file | cut -d= -f2)
    set -l c7  (grep "^TERMINAL_COLOR7="  $color_file | cut -d= -f2)
    set -l c8  (grep "^TERMINAL_COLOR8="  $color_file | cut -d= -f2)
    set -l c9  (grep "^TERMINAL_COLOR9="  $color_file | cut -d= -f2)
    set -l c10 (grep "^TERMINAL_COLOR10=" $color_file | cut -d= -f2)
    set -l c11 (grep "^TERMINAL_COLOR11=" $color_file | cut -d= -f2)
    set -l c12 (grep "^TERMINAL_COLOR12=" $color_file | cut -d= -f2)
    set -l c13 (grep "^TERMINAL_COLOR13=" $color_file | cut -d= -f2)
    set -l c14 (grep "^TERMINAL_COLOR14=" $color_file | cut -d= -f2)
    set -l c15 (grep "^TERMINAL_COLOR15=" $color_file | cut -d= -f2)

    echo "# Generated by apply-theme — DO NOT EDIT MANUALLY"  > ~/.config/kitty/theme.conf
    echo "background            #$bg"  >> ~/.config/kitty/theme.conf
    echo "foreground            #$fg"  >> ~/.config/kitty/theme.conf
    echo "cursor                #$acc" >> ~/.config/kitty/theme.conf
    echo "selection_background  #$sel" >> ~/.config/kitty/theme.conf
    echo "selection_foreground  #$bg"  >> ~/.config/kitty/theme.conf
    echo "color0  #$c0"  >> ~/.config/kitty/theme.conf
    echo "color1  #$c1"  >> ~/.config/kitty/theme.conf
    echo "color2  #$c2"  >> ~/.config/kitty/theme.conf
    echo "color3  #$c3"  >> ~/.config/kitty/theme.conf
    echo "color4  #$c4"  >> ~/.config/kitty/theme.conf
    echo "color5  #$c5"  >> ~/.config/kitty/theme.conf
    echo "color6  #$c6"  >> ~/.config/kitty/theme.conf
    echo "color7  #$c7"  >> ~/.config/kitty/theme.conf
    echo "color8  #$c8"  >> ~/.config/kitty/theme.conf
    echo "color9  #$c9"  >> ~/.config/kitty/theme.conf
    echo "color10 #$c10" >> ~/.config/kitty/theme.conf
    echo "color11 #$c11" >> ~/.config/kitty/theme.conf
    echo "color12 #$c12" >> ~/.config/kitty/theme.conf
    echo "color13 #$c13" >> ~/.config/kitty/theme.conf
    echo "color14 #$c14" >> ~/.config/kitty/theme.conf
    echo "color15 #$c15" >> ~/.config/kitty/theme.conf

    # Kitty'ye canlı reload sinyali gönder (yeniden başlatma gerekmez)
    kill -SIGUSR1 (pgrep -x kitty) 2>/dev/null
    echo ":: Kitty renkleri güncellendi (16 renk)."

    # ── 4. Hyprland border renkleri ───────────────────────────────────────────
    echo ":: [4/4] Hyprland border renkleri..."
    set -l border_focus   (grep "^WM_BORDER_FOCUS="   $color_file | cut -d= -f2)
    set -l border_unfocus (grep "^WM_BORDER_UNFOCUS=" $color_file | cut -d= -f2)
    echo ":: Accent (border focus):   #$border_focus"
    echo ":: Unfocus (border):        #$border_unfocus"
    echo ":: Hyprland için bu renkleri hyprland.conf'a elle yapıştırın veya 'apply-theme-hypr' çalıştırın."

    echo ""
    echo ":: ŞEHİR BOMBALANDI! hlorange paleti sisteme yayıldı."
    echo ":: Son adım: nwg-look açıp GTK temasını 'hlorange' olarak seçin."
end
