exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --primary --type text --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-clip-persist --clipboard primary
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprlock

# ═══════════════════════════════════════════════════════════════════════════════
# PLUGINS - hyprpm ile yüklenen pluginler
# ═══════════════════════════════════════════════════════════════════════════════
exec-once = hyprpm reload

exec-once = dunst
exec-once = quickshell

# Dashboard (special workspace)
